#!/bin/sh

usage() {
  echo "Usage: $0 [-f <test-function-name>] <scad-file>"
  exit
}

TEST_FUNCTION=test
while getopts "hf:" opt
do
  case ${opt} in
    f)
      TEST_FUNCTION="$OPTARG"
    ;;

    h | \?)
      usage
    ;;

    *)
      echo "invalid option or argument $OPTARG"
      exit 1
    ;;
  esac
done
shift $(( OPTIND - 1 ))
FILES="$*"

NC='\033[0m'
CYAN='\033[0;36m'
RED='\033[0;31m'
GREEN='\033[0;32m'

TEMP_OUT=`mktemp -t testXXXXXXXX.stl`
for f in $FILES
do
  OUTPUT=`echo "assert(${TEST_FUNCTION}()); cube([${TEST_FUNCTION}(), 1, 1]);" | cat "$f" - | "${OPENSCAD:-openscad}" -o "$TEMP_OUT" - 2>&1`
  RESULT=$?
  rm "$TEMP_OUT"

  if [ $RESULT -eq 0 ]
  then
    echo "$GREEN[PASS]$NC $f : $TEST_FUNCTION"
  else
    echo "$CYAN[TEST]$NC $f : $TEST_FUNCTION"
    echo "$OUTPUT"
    echo "$RED[FAIL]$NC $f : $TEST_FUNCTION"
  fi
done
